print("Calculate your BMI")
print("What is your height? in meter format")
height = input()
bmi_type_height = float(height)
print("What is your weight? in kg format")
weight = input()
bmi_type_weight= float(weight)
bmi = bmi_type_weight / (bmi_type_height * bmi_type_height)
print("Your BMI is:")
print(round(bmi, 2))
